id: IFF6168F2
legacy_id: P008087
ocr_import_info:
  bdrc_scan_id: W1KG13989
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T17:32:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:49:11.380900+00:00'
last_modified: 2022-08-31 14:50:03.030112
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13989
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13989
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དུང་དཀར་ཆོས་རྗེའི་གཅེས་ཉར་དཔེ་ཚོགས། ༼དུམ་བུ་ལྔ་པ།༽
statistics:
  ocr_word_mean_confidence_index: 0.6201272889873175
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I1KG85558:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG85558
      total_pages: 331
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG85558.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6193343978615375
    legacy_id: v002
  I1KG85559:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG85559
      total_pages: 495
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG85559.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5742417175940889
    legacy_id: v003
  I1KG85560:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG85560
      total_pages: 612
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG85560.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6587408134179318
    legacy_id: v004
  I1KG85557:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG85557
      total_pages: 583
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG85557.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6883016314967619
    legacy_id: v001
  I1KG85562:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG85562
      total_pages: 440
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG85562.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5477064844054796
    legacy_id: v006
  I1KG85561:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG85561
      total_pages: 224
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG85561.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5687460716706095
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
