id: IFF6168F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:35:19+00:00'
last_modified: '2022-06-09T04:24:18.600692+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13989
  title: དུང་དཀར་ཆོས་རྗེའི་གཅེས་ཉར་དཔེ་ཚོགས། ༼དུམ་བུ་ལྔ་པ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    490D:
      image_group_id: I1KG85557
      title: Volume 1 of dung dkar chos rje'i gces nyar dpe tshogs/ (dum bu lnga pa/)
      total_pages: 583
      order: 1
      base_file: 490D.txt
    34DD:
      image_group_id: I1KG85558
      title: Volume 2 of dung dkar chos rje'i gces nyar dpe tshogs/ (dum bu lnga pa/)
      total_pages: 331
      order: 2
      base_file: 34DD.txt
    443D:
      image_group_id: I1KG85559
      title: Volume 3 of dung dkar chos rje'i gces nyar dpe tshogs/ (dum bu lnga pa/)
      total_pages: 495
      order: 3
      base_file: 443D.txt
    B28D:
      image_group_id: I1KG85560
      title: Volume 4 of dung dkar chos rje'i gces nyar dpe tshogs/ (dum bu lnga pa/)
      total_pages: 612
      order: 4
      base_file: B28D.txt
    '9317':
      image_group_id: I1KG85561
      title: Volume 5 of dung dkar chos rje'i gces nyar dpe tshogs/ (dum bu lnga pa/)
      total_pages: 224
      order: 5
      base_file: 9317.txt
    F6CB:
      image_group_id: I1KG85562
      title: Volume 6 of dung dkar chos rje'i gces nyar dpe tshogs/ (dum bu lnga pa/)
      total_pages: 440
      order: 6
      base_file: F6CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
