id: P008087
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13989
  title: དུང་དཀར་ཆོས་རྗེའི་གཅེས་ཉར་དཔེ་ཚོགས། ༼དུམ་བུ་ལྔ་པ།༽
  author: ''
  volumes:
    1111b549594342f99b3d067485f53b53:
      image_group_id: I1KG85557
      title: ''
      volume_number: 1
      total_pages: 583
    7c8768bd7bbe4e96abda76c4d2dcae10:
      image_group_id: I1KG85558
      title: ''
      volume_number: 2
      total_pages: 331
    60e1997bcd8e4137b61d58458c45ad3b:
      image_group_id: I1KG85559
      title: ''
      volume_number: 3
      total_pages: 495
    015a3e3dc2cd4ed683b1f931ef739313:
      image_group_id: I1KG85560
      title: ''
      volume_number: 4
      total_pages: 612
    bf94df6eea914559ba81f42a835d176f:
      image_group_id: I1KG85561
      title: ''
      volume_number: 5
      total_pages: 224
    c3f6556e3944429faacaad11fa152e89:
      image_group_id: I1KG85562
      title: ''
      volume_number: 6
      total_pages: 440
ebook_metadata:
  title: དུང་དཀར་ཆོས་རྗེའི་གཅེས་ཉར་དཔེ་ཚོགས། ༼དུམ་བུ་ལྔ་པ།༽
  author: ''
  sku: P008087
  cover: cover.jpg
  layers:
  - pagination
